### ISSUE TITLE
Documentation + self.w unused

### ISSUE THREAD

**Issue by normanius** [siavashk/pycpd#12]
Hi Siavash

Just a few details:
- would be great if there was some bit of code documentation (mainly constructor arguments and returned objects)
- the self.w does not have any effect on the result

In any case great work! Thanks a lot for your efforts.
Cheers, Norman

**Comment by siavashk** [comment]
Hi Norman,

Thank you for the code review. I am always happy when I receive them. Please do tell me if you find anything else. Regarding your two points:

- Documentation: I would love to, but I just haven’t gotten into that. My day job keeps me pretty buys. Sorry about that!

- self.w is the contribution of the uniform distribution to mixture model. It is used in the EStep function of each registration class. See equations (2) and (6) in Myrorenko and Song’s [paper](https://arxiv.org/pdf/0905.2635.pdf): 

> We also added an additional uniform distribution to the mixture model to account for noise and outliers. Denoting the weight of the uniform distribution as w...

**Comment by normanius** [comment]
No worries regarding the documentation. Would have been handy though.

Regarding the second point: I see that `self.w` (lowercase w) is used in Estep() to compute the variable lowercase `c`. However `c` is never used, so `self.w` has no effect in the end. I am referring to [`deformable_registration()`](https://github.com/siavashk/pycpd/blob/master/pycpd/deformable_registration.py).

Do I oversee something?

**Comment by siavashk** [comment]
Good catch. I forgot to add it to the denominator. Probably [here](https://github.com/siavashk/pycpd/blob/15e3e8a30bdadf99cecb4b3554e43411f411eb9e/pycpd/deformable_registration.py#L101).

**Comment by siavashk** [comment]
Fixed in 3a22216b5d8bf3e035ec06afab6d33862be2021e
