### ISSUE TITLE
build from source and can't find "expectation_maximization_registration" module

### ISSUE THREAD

**Issue by sandyhsia** [siavashk/pycpd#16]
Hi, 
I choose to build from source and I encounter the error message like this:
![image](https://user-images.githubusercontent.com/15709515/43813626-1375f5c6-9af9-11e8-8b76-d690d0a4d895.png)

Generally, it says it fails with this line when running `__init__.py`:
`from expectation_maximization_registration import expectation_maximization_registration` in affine_registration.py.

I found that change the above line to 
`from .expectation_maximization_registration import expectation_maximization_registration` 
in every file in `__init__.py` solved this import problem.

**Comment by siavashk** [comment]
Fixed in e8cef82624f882a8805eab4c7cb033f9bda0f6e2.
