### ISSUE TITLE
bug in pycpd/rigid_registration.py

### ISSUE THREAD

**Issue by Kai-46** [siavashk/pycpd#21]
I believe that line 41 should be
            return self.s * np.dot(Y, self.R) + np.tile(self.t, (Y.shape[0], 1))
instead of the current
           return self.s * np.dot(Y, self.R) + np.tile(np.transpose(self.t), (Y.shape[0], 1))

**Comment by siavashk** [comment]
Good catch. I have been refactoring things and I missed this one.

**Comment by siavashk** [comment]
Fixed in 18fec52b9e43dda9684a770f11d1400c15dc5c09.

**Comment by siavashk** [comment]
I have also added you to [THANKS.txt](https://raw.githubusercontent.com/siavashk/pycpd/master/THANKS.txt).
