### ISSUE TITLE
Coherent Point Drift with STL files

### ISSUE THREAD

**Issue by stevenagl12** [siavashk/pycpd#28]
You wouldn't have any advice for how to use your code with stl files to perform the rigid and non-rigid registration for statistical shape modelling would you?

**Comment by siavashk** [comment]
You can read the fixed and moving meshes using an STL reader, for example [this](https://pypi.org/project/numpy-stl/), and extract their vertices. You can then use rigid, affine or deformable registration to align the vertices from the two meshes similar to the scripts under the `examples` directory.
