### ISSUE TITLE
UserWarning: This figure includes Axes that are not compatible with tight_layout

### ISSUE THREAD

**Issue by aaman-ee** [siavashk/pycpd#30]
Hi, when I try to run your examples in Pycharm (fish_deformable_2D.py), I get the following error:
`/snap/pycharm-professional/151/helpers/pycharm_matplotlib_backend/backend_interagg.py:64: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  self.figure.tight_layout()`
and only the initial figure is displayed correctly with all the iteration figures empty
![myplot1](https://user-images.githubusercontent.com/22389033/63933691-72044900-ca62-11e9-82c3-4f5273a920dc.png)
![myplot2](https://user-images.githubusercontent.com/22389033/63933754-83e5ec00-ca62-11e9-9e66-c067c65b52f3.png)

**Comment by siavashk** [comment]
This seems to be a compatibility issue between Pycharm and Matplotlib. You might want to try disabling the scientific plot window so that it would use the default backend:

File > Settings > Tools >  Python > show plots in tool window

Alternatively, you can try to removing the tight_layout option.

**Comment by siavashk** [comment]
Feel free to post a comment here if this does not solve your issue. I am closing it for now.

**Comment by Ritchizh** [comment]
I had the same plotting issue: the first iteration was plotted, but others were blank.
Changing the code as follows worked for me:

```
pic_num =1

def visualize(iteration, error, X, Y, ax):

    global pic_num
    fig = plt.figure(pic_num)
    ax = fig.add_subplot(111, projection='3d')

    ax.scatter(X[:, 0],  X[:, 1], X[:, 2], color='red', label='Target')
    ax.scatter(Y[:, 0],  Y[:, 1], Y[:, 2], color='blue', label='Source')
    ax.text2D(0.87, 0.92, 'Iteration: {:d}'.format(
        iteration), horizontalalignment='center', verticalalignment='center', transform=ax.transAxes, fontsize='x-large')
    ax.legend(loc='upper left', fontsize='x-large')

    pic_num +=1
```
(To make it 2D: ` ax = fig.add_subplot(111)` )
