### ISSUE TITLE
rigid transformation

### ISSUE THREAD

**Issue by mingweiY** [siavashk/pycpd#34]
Thanks for the code.  
Now I have two sets of points, one is a template, and the other is the same as the template but has some noisy points and is rotated 90 degrees. When I used the rigid method to register these two sets, I found that the effect was not ideal.  The rigid transformation include translation, rotation, and scaling. What is the reason for this?
Looking forward to your reply, thanks again.
[16535_fusept.txt](https://github.com/siavashk/pycpd/files/3999438/16535_fusept.txt)
[FormTax_00013_fusept.txt](https://github.com/siavashk/pycpd/files/3999439/FormTax_00013_fusept.txt)

**Comment by siavashk** [comment]
What do you mean by "the effect was not ideal"?

**Comment by siavashk** [comment]
Closed due to inactivity.

**Comment by KingDeng005** [comment]
Hi siavashk, for the regid transformation, why scaling was computed? For my case, I computed rigid transform for two point clouds in 2D, and s_reg returns a non 1 value. It then made it non-rigid am I missing something?

**Comment by ckolluru** [comment]
Hi, thanks for your work. Is there a way to get a rigid transformation result without any scaling?

There is no scaling effect between the two point clouds in my application. Thanks.

**Comment by gattia** [comment]
Hey, @ckolluru  - can you open a new issue?

**Comment by ckolluru** [comment]
I think this works. 

Just one more question - with scaling disabled, is it reasonable to expect that the diagonal elements in the final transformation be very close to 1? 0.99 or higher?

**Comment by gattia** [comment]
did you try this? If so, please feel free to make the changes on a development branch of your own fork of the repository and contribute back - others would really benefit from the addition. 

That's a great question, not necessarily. They will only be close to 1.0 if the registration didn't rotate the object very much. [This](https://en.wikipedia.org/wiki/Rotation_matrix#In_three_dimensions) describes how a 3D rotation matrix should look.... you can see that all of the diagonal elements are describes as cos(theta)... therefore, if theta (the change in angle) is close to zero, then the element will be close to one. If you make the angle bigger, these elements will change accordingly.

Also.. pycpd does the scaling separate from the rotation matrix: [here](https://github.com/siavashk/pycpd/blob/489a6b8b591c976e61ad46915b64622b587a8454/pycpd/rigid_registration.py#L117), so this shouldn't affect the rotation matrix at all.

**Comment by ckolluru** [comment]
Submitted a PR, please take a look when you can and let me know if I can do anything else.

**Comment by gattia** [comment]
Ability to select whether scaling is included in rigid registration has been added & merged to dev: https://github.com/siavashk/pycpd/pull/67
