### ISSUE TITLE
Merge Development

### ISSUE THREAD

**Issue by gattia** [siavashk/pycpd#35]
Hey, 

Just leaving a small note about maybe merging development with master. There are lots of good documentation additions that you added that the end-user is not getting. Also, I know you merged some of my changes with development where there were small errors in the implementation and would be useful for anyone blindly using this implementation to get those.

**Comment by siavashk** [comment]
Sorry. I have been busy for the past week. You are right,  I might do it over the long weekend. Stay safe!

**Comment by gattia** [comment]
No worries. Life does tend to get in the way of these things. Let me know if I can be of assistance.

**Comment by siavashk** [comment]
Fixed in 3b0d10f6029ef6fdccfd231417e2cc1afbe58024.
