### ISSUE TITLE
Running Examples - Plot not showing 

### ISSUE THREAD

**Issue by ssheridan17** [siavashk/pycpd#42]
Hi, 

When running examples only the first iteration and their respective point placements appear on the plot. The following iterations do not appear and I am unsure why. 

Thank you in advance!

**Comment by gattia** [comment]
Can you provide some more information? What examples? Is it all of them? What environment? Are you running them from the command line? Any other information that you have would be helpful.

**Comment by siavashk** [comment]
Is your issue similar to https://github.com/siavashk/pycpd/issues/30?

**Comment by ssheridan17** [comment]
Yes, my issue was the same #30 thank you so much!

**Comment by Ritchizh** [comment]
I had the same plotting issue: the first iteration was plotted, but others were blank.
Changing the code as follows worked for me:

```
pic_num =1

def visualize(iteration, error, X, Y, ax):

    global pic_num
    fig = plt.figure(pic_num)
    ax = fig.add_subplot(111, projection='3d')

    ax.scatter(X[:, 0],  X[:, 1], X[:, 2], color='red', label='Target')
    ax.scatter(Y[:, 0],  Y[:, 1], Y[:, 2], color='blue', label='Source')
    ax.text2D(0.87, 0.92, 'Iteration: {:d}'.format(
        iteration), horizontalalignment='center', verticalalignment='center', transform=ax.transAxes, fontsize='x-large')
    ax.legend(loc='upper left', fontsize='x-large')

    pic_num +=1
```
(To make it 2D: ` ax = fig.add_subplot(111)` )

**Comment by sandwich25** [comment]
Hi, I have the same problem and I'm using Spyder with python 3.6. Only the result for the first iteration is showed as shown in the attachment.

Thank you in advance.
<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/69758962/90420538-71dddd00-e0fb-11ea-98aa-220cd6d0e35f.png">

**Comment by siavashk** [comment]
@sandwich25 this seems to be a compatibility issue between matplotlib and spyder. I do not use spyder as an integrated development environment (IDE), so I cannot give you a definitive answer. The solution is probably similar to https://github.com/siavashk/pycpd/issues/30#issuecomment-531438477. 

I would suggest looking into the plotting options in your IDE. The answers in this [Stackoverflow question](https://stackoverflow.com/questions/23585126/how-do-i-get-interactive-plots-again-in-spyder-ipython-matplotlib) might help you.
