### ISSUE TITLE
Deformable registration - alpha and beta

### ISSUE THREAD

**Issue by agporto** [siavashk/pycpd#46]
Hi, Thanks for this great library. I have a question that  I was wondering if you would be able to answer. If I understand correctly, parameters alpha and beta in the deformable registration step should be scale dependent. In other words, if I were doing two separate registrations (one of small objects, other of large objects), the ideal values for those parameters should be different. Is that your understanding? If so, any chance you would have an idea of how alpha and beta change with the size of the structure?

**Comment by siavashk** [comment]
Related to #27.

>  if I were doing two separate registrations (one of small objects, other of large objects), the ideal values for those parameters should be different.

For β, it will depend on the distance between points in the point cloud. Basically β controls how close points should be to each other so that we treat them as a group that should move together. For a large point cloud this is generally true.

⍺ controls the fuiditiy of the point cloud. It does not care if about the size of the object.

**Comment by agporto** [comment]
Thanks for the response! Highly appreciated.

**Comment by gattia** [comment]
@siavashk is the expert here and he gives good advice. 

One additional thought I’ve seen done is normalizing the point clouds. E.g., normalize min/max range to be in 0-1 range, or something to that effect. In that case, you may have smaller differences in the parameters between applications. However, you should probably still tune the optimal parameters for each application.

**Comment by agporto** [comment]
@gattia Thanks for the suggestion. That is the path that I ended up taking (basically, made the pointcloud fit in a cube of unit size). It seems much easier to deal with than trying to figure out the proper scaling of beta with the size of objects.
