### ISSUE TITLE
Incorrect Integer Division (?)

### ISSUE THREAD

**Issue by evolvedmicrobe** [siavashk/pycpd#47]
Quick question on this line:

https://github.com/siavashk/pycpd/blob/3b0d10f6029ef6fdccfd231417e2cc1afbe58024/pycpd/emregistration.py#L165

In python 3 this is floating point division, but in python 2 this looks like it will perform integer (floor) division, was this supposed to be floating point division under both versions?

**Comment by siavashk** [comment]
Good catch! Yes, I should've done `from __future__ import division`. This is a bug.

**Comment by evolvedmicrobe** [comment]
Awesome, thanks @siavashk for the quick response!
