### ISSUE TITLE
How to find corresponding points between target and source point clouds?

### ISSUE THREAD

**Issue by mirickmi** [siavashk/pycpd#58]
Hi, 

is there a way to access a matrix with indices that tells me which point from the target corresponds to which point from the source?

**Comment by gattia** [comment]
I wouldn’t usually use it that way. Instead, i would usually use one point cloud as the template and then wherever the points land on the target after registration those are the new points for the target. This guarantees one-to-one point correspondences. And If you want to register many point clouds together they all have this perfect correspondence to the one template.

**Comment by mirickmi** [comment]
Okay, thanks a lot for your fast reply! :-) I'm fairly new to this topic and probably misunderstood something.
