### ISSUE TITLE
[Documentation] Add contribution file with guidelines

### ISSUE THREAD

**Issue by rickie95** [siavashk/pycpd#71]
Part of reviewing process for JOSS acceptance (openjournals/joss-reviews/issues/4681)

I couldn't find clear instructions on how to participate in this project. Ideally you should provide a CONTRIBUTE file with some informations about:

- **How to contribute to the software** (e.g. how to create a pull request or minimum requirements for accept a PR )
- **How to report issues**: your procedure of choice for handle bug reports (is there a template to follow? is required to provide a minimum reproducible example? is ok just a simple issue opened on GitHub?)
- **How to reach support**: alternate channels where to get help (email, forum, ecc..)

**Comment by gattia** [comment]
Thank you for the comment! 

Closing because the following commit adds a `CONTRIBUTING.md` with extensive documentation on how to contribute and references it in the README. 

https://github.com/siavashk/pycpd/commit/08e8cf0b86018948e670cdf1d5e10b450c4547b1
