### ISSUE TITLE
repeat self.intialize() fails due to change in shape of self.t

### ISSUE THREAD

**Issue by tlambert03** [siavashk/pycpd#8]
registrations cannot be repeated because self.t changes shape during processing.
`self.t.shape == (1,3)`  after `__init__`,  but `self.t.shape == (3,)` after `self.register()`,  

so repeat calls to `self.register()` gives 
`ValueError: operands could not be broadcast together with shapes`
in the line:
`self.TY = self.s * np.dot(self.Y, np.transpose(self.R)) + np.repeat(self.t, self.M, axis=0)`
(or the corresponding line in affine_registration)

**Comment by siavashk** [comment]
Thanks. I will look into it tomorrow today.

**Comment by siavashk** [comment]
Fixed in 3ddd79e9445b89cdcd3cdc8135c3477fe4f7eb63

**Comment by siavashk** [comment]
By the way, I would be happy to review any of your pull requests for fixing bugs and adding more features. There is a [Thanks.txt](https://raw.githubusercontent.com/siavashk/pycpd/master/THANKS.txt) file which reflects those that have contributed to the repository.
