### ISSUE TITLE
 How do I calculate its registration accuracy？

### ISSUE THREAD

**Issue by bhjbvs** [siavashk/pycpd#88]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gattia** [comment]
There are many ways this could be done, and it is more about the type of analysis or study you are trying to conduct than the software itself. 

One simple example would be to apply a known transform to the data, then try to register to the original data and calculate some sort of error. 

I’m closing this issue as it seems off topic to the core of the library.
