### ISSUE TITLE
 'ConstrainedDeformableRegistration' object has no attribute 'low_rank'[BUG]

### ISSUE THREAD

**Issue by fengyasi** [siavashk/pycpd#89]
Hi
Sorry to disturb
When I use the **fish_constrained_deformable_3D.py** , it has the _**AttributeError: 'ConstrainedDeformableRegistration' object has no attribute 'low_rank'**_
All the code and data are from the example and data folders

**Describe` the bug**
AttributeError: 'ConstrainedDeformableRegistration' object has no attribute 'low_rank'

**Comment by gattia** [comment]
@agporto - do you mind taking a look at this example?

**Comment by agporto** [comment]
@fengyasi @gattia Cannot replicate on my end. My guess is that the low_rank attribute was improperly called (it has to go inside the curly brackets). Please see example in https://github.com/siavashk/pycpd/blob/master/examples/fish_deformable_3D_lowrank.py . It contains the low_rank example of the fish_constrained_deformable_3D.  If the problem persists, please reopen with more details (package versions, etc)
