### ISSUE TITLE
[FEATURE] quality grading of final result

### ISSUE THREAD

**Issue by rejuce** [siavashk/pycpd#92]
I know from ICP method there is in the end a MSE, of all points that were consinderd in the transformation that could be used as quality criteria how well the fit worked / matched.

is there something similar here that I can use?

![grafik](https://github.com/user-attachments/assets/c5a19862-c115-4a03-831f-c90512b05a22)
for example the transformed point cloud (blue) to the partial profile (red) looks like this. slicing the cad data at 0+-0.01mm yields the right curve. now i want smt like the MSE between the source and target pcd. I can do something myself, just want check if there is nothing inbuilt that I can use as quality factor

**Comment by gattia** [comment]
The results look great. The built in metric used for fitting isn't interpretable like MSE. I would typically recommend something like ASSD, but for your base I think that would be quite bad. You probably only want to look at the points in your single line and for each point find the closest point on the cylinder and compute the MSE for these.

**Comment by rejuce** [comment]
i see too bad, thanks.  i ended up using piecewise linear interpoaltion of both regions and calculating normalised mse / abs error. now continur experimenting fitting a 3D data point cloud to, thanks for your work on the lib, very helpful for prototyping
